version: '3'

services:

    # Django app
    app: 
        build:
            context: app
            target: builder
        # image: seosite-app
        container_name: seosite-app
        restart: always
        depends_on:
            db:
                condition: service_healthy
        ports:
            - '80:8000'
        networks:
            - seosite_backend
        volumes:
            - ./app/seosite:/app
        environment:
            - OPENAI_API_KEY=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

    # Database 
    db:
        image: mysql
        container_name: seosite-db
        restart: always
        networks:
            - seosite_backend
        volumes:
            - ./db/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: hgztg543wer65zrt
        healthcheck:
            test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
            start_period: 20s
            interval: 5s
            retries: 10

    
    # adminer:
    #     image: adminer
    #     container_name: seosite_adminer
    #     restart: always
    #     links:
    #         - db:db
    #     ports:
    #         - 8080:8080

networks:
    seosite_backend:
        name: seosite_backend
        external: false