version: '3'

services:

    # Site #1 default
    deninos-app: 
        build:
            context: app
            target: builder
        # image: seosite-app
        container_name: deninos-app
        restart: always
        volumes:
            - ./app/static:/static
            - ./sites/deninos/media:/media
        depends_on:
            seosite-db:
                condition: service_healthy
        networks:
            - seosite_backend
        env_file:
            - ./sites/deninos/.env

    globos-app: 
        build:
            context: app
            target: builder
        # image: seosite-app
        container_name: globos-app
        restart: always
        volumes:
            - ./app/static:/static
            - ./sites/globos/media:/media
        depends_on:
            seosite-db:
                condition: service_healthy
        networks:
            - seosite_backend
        env_file:
            - ./sites/globos/.env

    mejorestiendasonline-app: 
        build:
            context: app
            target: builder
        # image: seosite-app
        container_name: mejorestiendasonline-app
        restart: always
        volumes:
            - ./app/static:/static
            - ./sites/mejorestiendasonline/media:/media
        depends_on:
            seosite-db:
                condition: service_healthy
        networks:
            - seosite_backend
        env_file:
            - ./sites/mejorestiendasonline/.env

    # Database 
    seosite-db:
        image: mysql:8.2.0
        container_name: seosite-db
        restart: always
        command: --init-file /data/application/init.sql
        networks:
            - seosite_backend
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/init.sql:/data/application/init.sql
        env_file:
            - ./db/.env
        healthcheck:
            test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
            start_period: 20s
            interval: 5s
            retries: 50

    # Nginx Server
    seosite-nginx:
        container_name: seosite-nginx
        image: nginx:1.25.3-alpine-slim
        restart: always
        networks:
            - seosite_backend
        volumes:
            - ./app/static:/static
            - ./sites:/sites
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - /etc/letsencrypt/live/xn--denios-zwa.com/privkey.pem:/etc/nginx/ssl/xn--denios-zwa.com/privkey.pem
            - /etc/letsencrypt/live/xn--denios-zwa.com/fullchain.pem:/etc/nginx/ssl/xn--denios-zwa.com/fullchain.pem
            - /etc/letsencrypt/live/globos.shop/privkey.pem:/etc/nginx/ssl/globos.shop/privkey.pem
            - /etc/letsencrypt/live/globos.shop/fullchain.pem:/etc/nginx/ssl/globos.shop/fullchain.pem
            - /etc/letsencrypt/live/mejorestiendasonline.club/privkey.pem:/etc/nginx/ssl/mejorestiendasonline.club/privkey.pem
            - /etc/letsencrypt/live/mejorestiendasonline.club/fullchain.pem:/etc/nginx/ssl/mejorestiendasonline.club/fullchain.pem
        ports:
            - "80:80"
            - "443:443"

        depends_on:
            - deninos-app
            - globos-app
            - mejorestiendasonline-app

networks:
    seosite_backend:
        name: seosite_backend
        external: false