version: '3'

services:

    # Django app
    app: 
        build:
            context: app
            target: builder
        # image: seosite-app
        container_name: seosite-app
        restart: always
        depends_on:
            db:
                condition: service_healthy
        networks:
            - seosite_backend
        volumes:
            - ./app/seosite:/app
            - ./app/static:/static
            - ./app/uploads:/uplaods
        env_file:
            - ./app/.env

    # Database 
    db:
        image: mysql:8.2.0
        container_name: seosite-db
        restart: always
        networks:
            - seosite_backend
        volumes:
            - ./db/data:/var/lib/mysql
        env_file:
            - ./db/.env
        healthcheck:
            test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
            start_period: 20s
            interval: 5s
            retries: 10

    nginx:
        container_name: seosite-nginx
        image: nginx:1.25.3-alpine-slim
        networks:
            - seosite_backend
        volumes:
            - ./app/static:/static
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        depends_on:
            - app
    # adminer:
    #     image: adminer
    #     container_name: seosite_adminer
    #     restart: always
    #     links:
    #         - db:db
    #     ports:
    #         - 8080:8080

networks:
    seosite_backend:
        name: seosite_backend
        external: false

volumes:
    static: