version: '3'

services:

    # Site #1 default
    deninos-app: 
        build:
            context: app
            target: builder
        # image: seosite-app
        container_name: deninos-app
        restart: always
        depends_on:
            seosite-db:
                condition: service_healthy
        networks:
            - seosite_backend
        volumes:
            - ./app/seosite:/app
            - deninos_static:/static
            - deninos_uploads:/uplaods
        env_file:
            - ./sites/deninos/.env

    # Site #1 default
    globos-app: 
        build:
            context: app
            target: builder
        # image: seosite-app
        container_name: globos-app
        restart: always
        depends_on:
            seosite-db:
                condition: service_healthy
        networks:
            - seosite_backend
        volumes:
            - ./app/seosite:/app
            - globos_static:/static
            - globos_uploads:/uplaods
        env_file:
            - ./sites/globos/.env

    # Database 
    seosite-db:
        image: mysql:8.2.0
        container_name: seosite-db
        restart: always
        command: --init-file /data/application/init.sql
        networks:
            - seosite_backend
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/init.sql:/data/application/init.sql
        env_file:
            - ./db/.env
        healthcheck:
            test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
            start_period: 20s
            interval: 5s
            retries: 50

    # Nginx Server
    seosite-nginx:
        container_name: seosite-nginx
        image: nginx:1.25.3-alpine-slim
        restart: always
        networks:
            - seosite_backend
        volumes:
            - ./app/static:/static
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "81:81"
        depends_on:
            - deninos-app
            - globos-app

networks:
    seosite_backend:
        name: seosite_backend
        external: false

    globos_static:
        name: globos_static
        external: false
    deninos_static:
        name: deninos_static
        external: false

    globos_uploads:
        name: globos_uploads
        external: false
    deninos_uploads:
        name: deninos_uploads
        external: false

volumes:
    static: