# Generated by Django 4.2.7 on 2023-11-25 12:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, unique=True)),
                ('slug', models.CharField(blank=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('keywords', models.TextField(blank=True, max_length=5000, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, max_length=20000, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('ext_ref', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
