# Generated by Django 4.2.7 on 2023-11-16 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_config_value_config_blog_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='blog_active',
        ),
        migrations.RemoveField(
            model_name='config',
            name='blog_theme',
        ),
    ]
