# Generated by Django 4.2.7 on 2023-11-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_config_blog_active_remove_config_blog_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='description_home',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='config',
            name='keywords_home',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
