# Generated by Django 4.2.7 on 2023-11-16 02:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_config_description_home_config_favicon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='description_home',
            field=tinymce.models.HTMLField(blank=True, max_length=20000, null=True),
        ),
    ]
