# Generated by Django 4.2.7 on 2023-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_category_publish_date_product_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='image_home',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
