# Generated by Django 4.2.7 on 2023-11-16 18:49

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_config_image_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='description_home',
        ),
        migrations.AddField(
            model_name='config',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='text_home',
            field=tinymce.models.HTMLField(blank=True, max_length=20000, null=True),
        ),
    ]
