# Generated by Django 4.2.7 on 2023-11-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_config_description_home_config_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='description',
            new_name='description_home',
        ),
    ]
