# Generated by Django 4.2.7 on 2023-11-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_category_publish_date_alter_config_shop_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='shop_active',
        ),
        migrations.RemoveField(
            model_name='config',
            name='shop_theme',
        ),
    ]
