# Generated by Django 4.2.7 on 2023-11-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_config_shop_active_remove_config_shop_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_width',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
