# Generated by Django 4.2.7 on 2023-11-18 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, unique=True)),
                ('slug', models.CharField(blank=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('keywords', models.TextField(blank=True, max_length=5000, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, max_length=20000, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('ext_ref', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='', width_field='image_width')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('canonical_url', models.URLField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='')),
                ('title_decorator', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('title_home', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description_home', models.TextField(blank=True, max_length=5000, null=True)),
                ('text_home', tinymce.models.HTMLField(blank=True, max_length=20000, null=True)),
                ('keywords_home', models.TextField(blank=True, max_length=5000, null=True)),
                ('image_home', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, unique=True)),
                ('slug', models.CharField(blank=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('keywords', models.TextField(blank=True, max_length=5000, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, max_length=20000, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('ext_ref', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', null=True, upload_to='', width_field='image_width')),
                ('image_width', models.IntegerField(blank=True, null=True)),
                ('image_height', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, unique=True)),
                ('slug', models.CharField(blank=True, max_length=254, unique=True)),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('keywords', models.TextField(blank=True, max_length=5000, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, max_length=20000, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('ext_ref', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='blog.category')),
                ('images', models.ManyToManyField(blank=True, related_name='posts', to='blog.image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=64)),
                ('author_img', models.URLField(blank=True, max_length=254, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
    ]
