# Generated by Django 4.2.7 on 2023-11-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_category_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='contact',
            field=models.CharField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
