CREATE DATABASE IF NOT EXISTS seosite;
CREATE DATABASE IF NOT EXISTS test_seosite;
CREATE DATABASE IF NOT EXISTS globos;
CREATE DATABASE IF NOT EXISTS test_globos;
CREATE DATABASE IF NOT EXISTS mejorestiendasonline;
CREATE DATABASE IF NOT EXISTS test_mejorestiendasonline;